export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  images: string[];
  category: string;
  hairType: string;
  laceType: string;
  length: string;
  density: string;
  capSize: string[];
  colors: string[];
  description: string;
  careInstructions: string[];
  rating: number;
  reviews: number;
  inStock: boolean;
  bestseller?: boolean;
  new?: boolean;
  collections?: string[];
}

export interface Collection {
  id: string;
  name: string;
  description: string;
  image: string;
  productCount: number;
}

export interface Review {
  id: string;
  author: string;
  avatar: string;
  rating: number;
  date: string;
  content: string;
  productName: string;
  verified: boolean;
}

export const collections: Collection[] = [
  {
    id: 'tms-gm01',
    name: 'TMS GM01',
    description: 'Make your Wedding Day Memorable',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_2.png',
    productCount: 6,
  },
  {
    id: 'adedotun',
    name: 'Adedotun',
    description: 'Revel in the regal allure of traditional Nigerian styles',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_5.png',
    productCount: 16,
  },
  {
    id: 'urban-safari',
    name: 'Urban Safari',
    description: 'Conquer the street with Afro inspired modern casual wears',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_DSC03812.jpg',
    productCount: 12,
  },
];

export const categories = [
  {
    id: 'agbada',
    name: 'Agbada',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_5.png',
  },
  {
    id: 'casual-wears',
    name: 'Casual Wears',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_Casual-Wear.png',
  },
  {
    id: 'kaftan',
    name: 'Kaftan',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_4.png',
  },
  {
    id: 'suits',
    name: 'Suits',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07043.jpg',
  },
  {
    id: 'shoes',
    name: 'Shoes',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_Shoe.png',
  },
  {
    id: 'bubu',
    name: 'Bubu',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0052.jpg',
  },
  {
    id: 'accessories',
    name: 'Accessories',
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_1-1.png',
  },
];

export const products: Product[] = [
  // === CASUAL WEARS ===
  {
    id: '1',
    name: 'TMS Abstract Brown Two Piece',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1303.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1303.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Brown'],
    description: 'Stylish abstract brown two piece casual wear. Perfect for outings and casual events.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat', 'Store on hanger'],
    rating: 4.8,
    reviews: 12,
    inStock: true,
    bestseller: false,
    collections: ['urban-safari'],
  },
  {
    id: '2',
    name: 'TMS Afro Double Two Piece',
    price: 100000,
    originalPrice: 160000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1321.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1321.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Bold Afro-inspired double two piece set. A statement outfit for the modern man.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.9,
    reviews: 18,
    inStock: true,
    bestseller: true,
    collections: ['urban-safari'],
  },
  {
    id: '3',
    name: 'TMS Afro Oceanic LongSleeve Two Piece',
    price: 90000,
    originalPrice: 130000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1309.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1309.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue', 'Green'],
    description: 'Oceanic-themed long sleeve two piece with vibrant Afro patterns.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.7,
    reviews: 9,
    inStock: true,
    collections: ['urban-safari'],
  },
  {
    id: '4',
    name: 'TMS Black Two Piece',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1330.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1330.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1327.jpg',
    ],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    description: 'Classic black two piece casual wear. Versatile and stylish for any occasion.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.8,
    reviews: 15,
    inStock: true,
    bestseller: true,
    collections: ['urban-safari'],
  },
  {
    id: '5',
    name: 'TMS Blue Two Piece',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0042.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0042.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    description: 'Vibrant blue two piece set for the fashion-forward gentleman.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.6,
    reviews: 8,
    inStock: true,
    collections: ['urban-safari'],
  },
  {
    id: '6',
    name: 'TMS Forest Green Two Piece',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3232.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3232.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Green'],
    description: 'Nature-inspired forest green two piece. Stand out with earthy elegance.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.7,
    reviews: 10,
    inStock: true,
    collections: ['urban-safari'],
  },
  {
    id: '7',
    name: 'TMS Oceanic Blue Two Piece',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1314-1.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1314-1.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    description: 'Deep oceanic blue two piece with premium fabric and contemporary design.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.8,
    reviews: 14,
    inStock: true,
    collections: ['urban-safari'],
  },
  {
    id: '8',
    name: 'TMS White and Black Afro Two Piece',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1323.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1323.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black'],
    description: 'Striking white and black Afro-inspired two piece. Bold contrast for maximum impact.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.9,
    reviews: 20,
    inStock: true,
    bestseller: true,
    collections: ['urban-safari'],
  },
  // === URBAN SAFARI COLLECTION ===
  {
    id: '9',
    name: 'TMS Urban Safari Afro Abstract',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3234.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3234.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3242.jpg',
    ],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Abstract Afro print two piece from the Urban Safari collection.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.7,
    reviews: 11,
    inStock: true,
    collections: ['urban-safari'],
  },
  {
    id: '10',
    name: 'TMS Urban Safari Crimson Red',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3209.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3209.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3218.jpg',
    ],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red'],
    description: 'Bold crimson red two piece from the Urban Safari collection.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.8,
    reviews: 16,
    inStock: true,
    new: true,
    collections: ['urban-safari'],
  },
  {
    id: '11',
    name: 'TMS Urban Safari Crimson Red and Palms Sea Blue',
    price: 80000,
    originalPrice: 120000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3227.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3227.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3240.jpg',
    ],
    category: 'casual-wears',
    hairType: 'Two Piece Set',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red', 'Blue'],
    description: 'A combo set of crimson red and palms sea blue two pieces from the Urban Safari collection.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.9,
    reviews: 22,
    inStock: true,
    bestseller: true,
    collections: ['urban-safari'],
  },
  {
    id: '12',
    name: 'TMS Urban Safari Palms Blue Long Sleeve',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3245.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3245.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_3235.jpg',
    ],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    description: 'Palm-printed long sleeve blue two piece from the Urban Safari collection.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.7,
    reviews: 13,
    inStock: true,
    collections: ['urban-safari'],
  },
  {
    id: '13',
    name: 'Urban Safari Blue Two Piece',
    price: 40000,
    originalPrice: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_IMG_3246-scaled.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_IMG_3246-scaled.jpg'],
    category: 'casual-wears',
    hairType: 'Two Piece',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    description: 'Classic blue two piece from the Urban Safari collection. Casual yet refined.',
    careInstructions: ['Dry clean recommended', 'Iron on low heat'],
    rating: 4.8,
    reviews: 25,
    inStock: true,
    bestseller: true,
    collections: ['urban-safari'],
  },
  // === KAFTANS ===
  {
    id: '14',
    name: 'TMS Abstract Kaftan Full Length',
    price: 60000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250219-WA0008.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250219-WA0008.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Abstract patterned full length kaftan. Elegant traditional wear with modern flair.',
    careInstructions: ['Dry clean only', 'Iron on medium heat', 'Store on hanger'],
    rating: 4.8,
    reviews: 14,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '15',
    name: 'TMS Black Kaftan Embroidery',
    price: 50000,
    originalPrice: 70000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1251.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1251.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    description: 'Luxurious black kaftan with intricate embroidery details.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.9,
    reviews: 19,
    inStock: true,
    bestseller: true,
    collections: ['adedotun'],
  },
  {
    id: '16',
    name: 'TMS Black Kaftan with Traditional Cap',
    price: 70000,
    originalPrice: 100000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1267.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1267.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    description: 'Premium black kaftan paired with a matching traditional cap.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.8,
    reviews: 16,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '17',
    name: 'TMS Black Kaftan without Embroidery',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1273.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1273.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    description: 'Elegant plain black kaftan for a clean, sophisticated look.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.7,
    reviews: 11,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '18',
    name: 'TMS Blue Kaftan',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1258.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1258.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1261.jpg',
    ],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    description: 'Stunning blue kaftan with premium fabric and tailored fit.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.8,
    reviews: 13,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '19',
    name: 'TMS Brown and Black Kaftan with Traditional Cap',
    price: 140000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1281.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1281.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Brown', 'Black'],
    description: 'Luxurious brown and black kaftan with matching traditional cap. A regal outfit.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.9,
    reviews: 21,
    inStock: true,
    bestseller: true,
    collections: ['adedotun'],
  },
  {
    id: '20',
    name: 'TMS Deep Brown Kaftan with Traditional Cap',
    price: 70000,
    originalPrice: 90000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1284.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1284.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Brown'],
    description: 'Rich deep brown kaftan with matching traditional cap.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.7,
    reviews: 10,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '21',
    name: 'TMS Kaftan and Bubu Double',
    price: 150000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20251111-WA0010.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20251111-WA0010.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan & Bubu',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Exclusive kaftan and bubu double set. Two premium outfits in one purchase.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.9,
    reviews: 24,
    inStock: true,
    bestseller: true,
    collections: ['adedotun'],
  },
  {
    id: '22',
    name: 'TMS Kaftan Double Blue and Black',
    price: 140000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1248.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1248.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan Double',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue', 'Black'],
    description: 'Premium double kaftan set in blue and black. Two distinct looks for the price of one.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.8,
    reviews: 17,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '23',
    name: 'TMS Kaftan with Traditional Cap',
    price: 70000,
    originalPrice: 100000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20251111-WA0011.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20251111-WA0011.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Elegant kaftan paired with a matching traditional cap. Complete the look.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.7,
    reviews: 12,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '24',
    name: 'TMS Kaftans Double with Caps',
    price: 140000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1254.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1254.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan Double',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Double kaftan set with matching traditional caps. Premium quality fabric.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.8,
    reviews: 15,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '25',
    name: 'TMS White Kaftan',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20241123-WA0074.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20241123-WA0074.jpg'],
    category: 'kaftan',
    hairType: 'Kaftan',
    laceType: '',
    length: 'Full Length',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White'],
    description: 'Pristine white kaftan for a clean, royal look. Perfect for special occasions.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.8,
    reviews: 18,
    inStock: true,
    new: true,
  },
  // === BUBU ===
  {
    id: '26',
    name: 'TMS Custom Bubu Kaftan',
    price: 60000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0038.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0038.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0040.jpg',
    ],
    category: 'bubu',
    hairType: 'Bubu',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    description: 'Custom designed bubu kaftan. A fusion of bubu and kaftan styles.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.7,
    reviews: 9,
    inStock: true,
    collections: ['adedotun'],
  },
  {
    id: '27',
    name: 'TMS Striped Black Bubu',
    price: 60000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0052.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0052.jpg'],
    category: 'bubu',
    hairType: 'Bubu',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    description: 'Sophisticated striped black bubu. A modern take on the classic bubu style.',
    careInstructions: ['Dry clean only', 'Iron on low heat'],
    rating: 4.6,
    reviews: 7,
    inStock: false,
    collections: ['adedotun'],
  },
  // === AGBADA ===
  {
    id: '28',
    name: 'TMS Green Agbada',
    price: 100000,
    originalPrice: 150000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0026.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG-20250218-WA0026.jpg'],
    category: 'agbada',
    hairType: 'Agbada',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Green'],
    description: 'Majestic green agbada for grand celebrations. Regal and commanding.',
    careInstructions: ['Dry clean only', 'Store on hanger', 'Iron on medium heat'],
    rating: 4.9,
    reviews: 20,
    inStock: true,
    bestseller: true,
  },
  {
    id: '29',
    name: 'TMS Adedotun Agbada Gold',
    price: 100000,
    originalPrice: 150000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07564.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07564.jpg'],
    category: 'agbada',
    hairType: 'Agbada',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Gold'],
    description: 'Golden agbada from the Adedotun collection. A showstopper at any event.',
    careInstructions: ['Dry clean only', 'Store on hanger'],
    rating: 4.9,
    reviews: 28,
    inStock: true,
    bestseller: true,
    new: true,
    collections: ['adedotun'],
  },
  {
    id: '30',
    name: 'TMS Adedotun Agbada Navy Blue',
    price: 100000,
    originalPrice: 150000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07693.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07693.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07681.jpg',
    ],
    category: 'agbada',
    hairType: 'Agbada',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy Blue'],
    description: 'Navy blue agbada from the Adedotun collection. Royal elegance personified.',
    careInstructions: ['Dry clean only', 'Store on hanger'],
    rating: 4.9,
    reviews: 26,
    inStock: true,
    bestseller: true,
    collections: ['adedotun'],
  },
  // === SUITS (TMS GM01) ===
  {
    id: '31',
    name: 'TMS Black Abstract Suit',
    price: 150000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1297.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1297.jpg'],
    category: 'suits',
    hairType: 'Suit',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    description: 'Abstract design black suit from the TMS GM01 collection. Make a bold statement.',
    careInstructions: ['Dry clean only', 'Store on suit hanger', 'Steam press recommended'],
    rating: 4.9,
    reviews: 22,
    inStock: true,
    bestseller: true,
    collections: ['tms-gm01'],
  },
  {
    id: '32',
    name: 'TMS Black and Gold Suits',
    price: 300000,
    originalPrice: 400000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1295.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1295.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1297.jpg',
    ],
    category: 'suits',
    hairType: 'Suit',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Gold'],
    description: 'Premium black and gold suit set from the TMS GM01 collection. The pinnacle of luxury.',
    careInstructions: ['Dry clean only', 'Store on suit hanger', 'Steam press recommended'],
    rating: 5.0,
    reviews: 30,
    inStock: true,
    bestseller: true,
    collections: ['tms-gm01'],
  },
  {
    id: '33',
    name: 'TMS Gold Suit',
    price: 150000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1291.jpg',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1291.jpg',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_10_IMG_1293.jpg',
    ],
    category: 'suits',
    hairType: 'Suit',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Gold'],
    description: 'Stunning gold suit from the TMS GM01 collection. Shine at every occasion.',
    careInstructions: ['Dry clean only', 'Store on suit hanger'],
    rating: 4.9,
    reviews: 25,
    inStock: true,
    collections: ['tms-gm01'],
  },
  {
    id: '34',
    name: 'TMS GM01 Blue Suit',
    price: 120000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07043.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07043.jpg'],
    category: 'suits',
    hairType: 'Suit',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    description: 'Classic blue suit from the TMS GM01 wedding collection. Timeless elegance.',
    careInstructions: ['Dry clean only', 'Store on suit hanger'],
    rating: 4.8,
    reviews: 19,
    inStock: true,
    new: true,
    collections: ['tms-gm01'],
  },
  {
    id: '35',
    name: 'TMS GM01 Golden Brown',
    price: 120000,
    originalPrice: 200000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07424.jpg',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_DSC07424.jpg'],
    category: 'suits',
    hairType: 'Suit',
    laceType: '',
    length: '',
    density: '',
    capSize: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Golden Brown'],
    description: 'Golden brown suit from the TMS GM01 wedding collection. Warm and sophisticated.',
    careInstructions: ['Dry clean only', 'Store on suit hanger'],
    rating: 4.8,
    reviews: 17,
    inStock: true,
    collections: ['tms-gm01'],
  },
  // === SHOES ===
  {
    id: '36',
    name: 'TMS Tanned Penny',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_1996.JPG',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_1996.JPG',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_1998.JPG',
    ],
    category: 'shoes',
    hairType: 'Loafers',
    laceType: 'Leather',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Tan'],
    description: 'Premium tanned penny loafers crafted with the finest leather.',
    careInstructions: ['Clean with a soft cloth', 'Apply leather conditioner regularly', 'Store with shoe trees'],
    rating: 4.9,
    reviews: 24,
    inStock: true,
    bestseller: true,
  },
  {
    id: '37',
    name: 'TMS Brown Suede Loafers',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2028.JPG',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2028.JPG'],
    category: 'shoes',
    hairType: 'Loafers',
    laceType: 'Suede',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Brown'],
    description: 'Elegant brown suede loafers with exceptional comfort and style.',
    careInstructions: ['Use suede brush for cleaning', 'Apply waterproof spray', 'Avoid wet conditions'],
    rating: 4.8,
    reviews: 18,
    inStock: true,
    bestseller: true,
  },
  {
    id: '38',
    name: 'TMS Black Straped Half Shoe',
    price: 50000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2036.JPG',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2036.JPG',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2034.JPG',
    ],
    category: 'shoes',
    hairType: 'Half Shoe',
    laceType: 'Leather',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Black'],
    description: 'Stylish black half shoe with custom straps.',
    careInstructions: ['Polish regularly', 'Store in dust bag', 'Use shoe horn when wearing'],
    rating: 4.7,
    reviews: 12,
    inStock: false,
  },
  {
    id: '39',
    name: 'TMS Black Penny with Custom Straps',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2037.JPG',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2037.JPG'],
    category: 'shoes',
    hairType: 'Loafers',
    laceType: 'Leather',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Black'],
    description: 'Black penny loafers elevated with custom straps for a unique, sophisticated look.',
    careInstructions: ['Clean with a soft cloth', 'Apply leather conditioner regularly'],
    rating: 4.9,
    reviews: 32,
    inStock: true,
    bestseller: true,
  },
  {
    id: '40',
    name: 'TMS Brown Penny Loafers',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2042.JPG',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2042.JPG',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2042-1.JPG',
    ],
    category: 'shoes',
    hairType: 'Loafers',
    laceType: 'Leather',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Brown'],
    description: 'Classic brown penny loafers with premium leather finishing.',
    careInstructions: ['Clean with a soft cloth', 'Apply leather conditioner regularly', 'Store with shoe trees'],
    rating: 4.8,
    reviews: 28,
    inStock: true,
  },
  {
    id: '41',
    name: 'TMS Brown Party Shoe',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2047-1.JPG',
    images: [
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2047-1.JPG',
      'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2051.JPG',
    ],
    category: 'shoes',
    hairType: 'Party Shoes',
    laceType: 'Leather',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Brown'],
    description: 'Premium brown party shoes designed for special occasions.',
    careInstructions: ['Polish regularly', 'Store in dust bag'],
    rating: 4.7,
    reviews: 15,
    inStock: true,
    new: true,
  },
  {
    id: '42',
    name: 'TMS Blue Half Shoe',
    price: 30000,
    originalPrice: 40000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2061.JPG',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2061.JPG'],
    category: 'shoes',
    hairType: 'Half Shoe',
    laceType: 'Suede',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Blue'],
    description: 'Unique blue half shoes in premium suede. A bold fashion statement.',
    careInstructions: ['Use suede brush for cleaning', 'Apply waterproof spray'],
    rating: 4.6,
    reviews: 9,
    inStock: true,
  },
  {
    id: '43',
    name: 'TMS Brown Penny Shoes',
    price: 50000,
    originalPrice: 80000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2055-1.JPG',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2055-1.JPG'],
    category: 'shoes',
    hairType: 'Loafers',
    laceType: 'Leather',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Brown'],
    description: 'Signature brown penny shoes with exceptional craftsmanship.',
    careInstructions: ['Clean with a soft cloth', 'Apply leather conditioner regularly'],
    rating: 4.8,
    reviews: 22,
    inStock: true,
    bestseller: true,
  },
  {
    id: '44',
    name: 'TMS Wine Half Shoe',
    price: 30000,
    originalPrice: 40000,
    image: 'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2058.JPG',
    images: ['https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_11_IMG_2058.JPG'],
    category: 'shoes',
    hairType: 'Half Shoe',
    laceType: 'Suede',
    length: '',
    density: '',
    capSize: ['40', '41', '42', '43', '44', '45'],
    colors: ['Wine'],
    description: 'Sophisticated wine-colored half shoes in premium suede.',
    careInstructions: ['Use suede brush for cleaning', 'Apply waterproof spray'],
    rating: 4.7,
    reviews: 11,
    inStock: true,
    new: true,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Adeola T.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    rating: 5,
    date: '2 weeks ago',
    content: 'The quality of these shoes is unmatched! I wore the TMS Tanned Penny to a wedding and got so many compliments. Will definitely order again!',
    productName: 'TMS Tanned Penny',
    verified: true,
  },
  {
    id: '2',
    author: 'Chukwudi K.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
    rating: 5,
    date: '1 month ago',
    content: 'The Adedotun collection is magnificent. Traditional Nigerian fashion at its finest. The craftsmanship and attention to detail are incredible.',
    productName: 'Adedotun Collection',
    verified: true,
  },
  {
    id: '3',
    author: 'Oluwaseun R.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80',
    rating: 5,
    date: '3 weeks ago',
    content: 'Fast shipping to Lagos and the agbada came beautifully packaged. It is now my go-to for special occasions. Absolutely love it!',
    productName: 'TMS GM01 Agbada',
    verified: true,
  },
  {
    id: '4',
    author: 'Babatunde M.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80',
    rating: 5,
    date: '1 week ago',
    content: 'Exceeded my expectations! The Urban Safari collection is trendy yet rooted in African culture. Best fits indeed!',
    productName: 'Urban Safari Casual',
    verified: true,
  },
];

export const instagramPosts = [
  'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_1-1.jpg',
  'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_2-1.jpg',
  'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_3.jpg',
  'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_4.jpg',
  'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_5.jpg',
  'https://uyupxiwhdvrhwtipanrm.supabase.co/storage/v1/object/public/site-assets/images/2025_09_6.jpg',
];
